language: elixir

elixir:
  - 1.3.4
  - 1.4.4

otp_release:
  - 18.0
  - 19.1
  - 19.3

matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 19.3

script:
  - mix deps.get
  - mix test --cover
  - mix dogma

branches:
  only:
    - master
