language: elixir

elixir:
  - 1.4.4
  - 1.5.1

otp_release:
  - 19.3
  - 20.0

matrix:
  exclude:
  - elixir: 1.4.4
    otp_release: 20.0

script:
  - mix deps.get
  - mix test --cover
  - mix dogma

branches:
  only:
    - master
